<b>1 - INFORMACIÓN IMPORTANTE.</b><br>
Se recomienda leer muy atentamente los siguientes Términos y Condiciones de Servicio. El ingreso en esta comunidad, el simple hecho de pertenecer a ella, el uso que se haga de ella y la adquisición de nuestros servicios y productos implica que se han leído y aceptado estos Términos y Condiciones de Servicio.
<br><br>
<b>2 - CONTENIDO, TÉRMINOS LEGALES Y RESPONSABILIDADES.</b><br>
La web, bewom.es, contiene herramientas necesarias para el desarrollo de una comunidad de usuarios y otros contenidos elaborados por la propia comunidad y sus responsables. Dichos contenidos podrán ser modificados y/o sustituidos por unos nuevos sin notificación previa ni responsabilidad alguna.
<br>bewom.es se reserva el derecho pero y se compromete a retirar cualquier comentario o aportación que no considere adecuado para su publicación, incluyendo:
<br>
    <br>comentarios o aportaciones xenófobos, racistas o discriminatorios en general que atenten contra la integridad de un individuo o colectivo
    <br>comentarios que vulneren derechos de las personas físicas o jurídicas, tales como el derecho a la dignidad y privacidad de las personas
    <br>comentarios que atenten contra la juventud o la infancia
    <br>comentarios que atenten o difamen a bewom.es. En ningún caso bewom.es se hará responsable de las opiniones y comentarios de los usuarios a través de cualquier servicio.
<br>
Cuando el usuario accede a la web lo hace por su propia cuenta y riesgo. bewom.es no garantiza la rapidez, la ininterrupción y la ausencia de virus o pérdida de datos en la web. Asimismo, los titulares de la web y los colaboradores y representantes tampoco podrán ser considerados responsables por cualesquiera daños derivados de la utilización de esta web, ni por cualquier actuación realizada sobre la base de la información que en ella se encuentra.
<br>En el caso de existir enlaces a distintas páginas web, y estos contengan enlaces con contenido con copyright, bewom.es se hace responsable de eliminar y denunciar al usuario que lo realice.
<br><br>
<b>3 - POLÍTICA DE PRIVACIDAD.</b><br>
Los datos de carácter personal que se hayan obtenido a través de la web tendrán la protección necesaria a fin de evitar su alteración, pérdida o acceso no autorizados. Dichos datos no se usarán con otro fin que no sea identificar al usuario. Las contraseñas de acceso a las distintas cuentas se encuentran encriptadas en el servidor, por lo que sólo el propietario de esa cuenta tiene acceso a ella. Por ello, el usuario se hace responsable del mal uso que se pueda realizar directa o indirectamente de su cuenta. No pedimos ni almacenamos información de cobro de los usuarios interesados ni información de tarjetas de crédito o cuentas bancarias, sino que cualquier aportación de dinero a la comunidad (considerada donación y no pago) se efectuará mediante organizaciones y métodos externos no vinculados con bewom.es. Cualquier problema que pueda surgir durante el uso de dichos métodos de aportación de capital no está vinculado a bewom.es ni a los miembros de su dirección. Los datos que se recopilan en los pagos tendrán la finalidad exclusiva de identificar al usuario. Todos aquellos usuarios que faciliten sus datos a través de la web serán los únicos responsables de la información cedida y tendrán los derechos de acceso, rectificación y/o cancelación de sus datos sin oposición alguna. bewom.es no venderá a terceros ni usará con fines comerciales la información privada de registro del usuario.
<br><br>
<b>4 - PROPIEDAD INTELECTUAL.</b><br>
<br>La totalidad de los contenidos de esta web (textos, imágenes, sonido, ficheros, marcas, logotipos, combinaciones de colores o cualquier otro elemento, su estructura y diseño, la selección y la forma de presentación de los contenidos incluidos en el mismo) y de los servicios que ofrece son propiedad de los titulares de la web, y se publican bajo una licencia Creative Commons con las siguientes características:
<br>Se autoriza el almacenamiento y reproducción de alguno o algunos de los contenidos de la web, con el propósito de ser utilizados con un fin personal y exclusivamente no comercial, y condicionados a una referencia explícita a bewom.es y a su titularidad. El uso y la difusión de los contenidos de la web con fines comerciales queda terminantemente prohibido sin el previo consentimiento expreso y por escrito de los titulares de la web, y siempre que se haga referencia explícita a bewom.es y a su titularidad.
<br><br>
<b>5 - SERVICIOS PROPORCIONADOS Y USO DE SERVICIOS. </b><br>
bewom.es es una comunidad que se articula alrededor del acceso a un servidor de juego, concretamente de Minecraft™ (propiedad de Mojang AB y Microsoft, www.mojang.com, www.microsoft.com), además de cualquier servicio auxiliar que considere oportuno. Cualquier incidencia que tenga que ver directa o indirectamente con dicho juego o con los servicios auxiliares externos no será responsabilidad de bewom.es ni de su dirección. El acceso y uso de estos servicios se condicionará al respeto de estos Términos y Condiciones de Servicio, al conocimiento y cumplimiento de cualquier condición incluida en el apartado "Normas" de www.bewom.es, así como a cualquier aviso que se haga dentro del propio servidor o servicio. Al usar bewom.es o cualquiera de sus servicios, el usuario se compromete al conocimiento y cumplimiento de todas las condiciones mencionadas. 
<br>bewom.es se reserva el derecho a interrumpir sin previo aviso el acceso a cualquiera de sus servicios al usuario o usuarios que incumpla o incumplan estas condiciones. Asimismo, bewom.es se reserva el derecho a interrumpir sin previo aviso el acceso a la web y a cualquiera de los servicios que proporciona a cualquier número de usuarios bajo los criterios que considere oportunos, incluyendo pero no limitado a criterios técnicos, económicos o sociales, así como a ejercer control y uso de los datos dentro del servidor que crea apropiado, manteniendo siempre intacto el derecho a la privacidad del usuario. bewom.es se reserva el derecho a aceptar nuevos usuarios en cualquiera de sus servicios bajo los criterios que considere oportunos. bewom.es no garantiza la rapidez, ininterrupción y ausencia de virus de sus servicios, ni se hace responsable del uso que los usuarios particulares hagan de estos.
<br><br>
<b>6 - FINANCIACIÓN Y POLÍTICA DE DEVOLUCIÓN.</b><br>
bewom.es es una comunidad sin ánimo de lucro que ofrece servicios y productos de software, y que se financia a través de donaciones por parte de los usuarios de la comunidad. Al tener carácter de donación y no de pago por productos o servicios, bewom.es no se compromete en ningún caso a la devolución íntegra o parcial de la(s) cantidad(es) donada(s), incluyendo especialmente los supuestos de interrupción de servicios a usuarios que incumplan estos términos de uso y/o cualquier condición incluida en el apartado "Normas" de www.bewom.es. A cambio, bewom.es se compromete a destinar las cantidades íntegras recaudadas exclusivamente al mantenimiento y mejora y/o ampliación dentro de lo posible de los servicios que ofrece, siempre dentro de criterios técnicos, económicos y administrativos.
<br>Aceptar los Términos y Condiciones de Servicio de bewom.es implica haber leído y entendido este punto en especial, además de todos los otros, y estar de acuerdo con él.
<br><br>
<b>7 - SERVICIOS DE TERCEROS.</b><br>
Este sitio web utiliza o incluye servicios proporcionados por proveedores independientes, ajenos a la propia bewom.es, relativos a empresas como Adfly (http://www.ad.fly/) y otras empresas o proveedores de servicios. Es posible que algunos de estos proveedores puedan introducir cookies en el navegador del usuario para mostrar anuncios basados en visitas anteriores, o que utilicen etiquetas de seguimiento para recopilar información como consecuencia de la publicación de anuncios en el sitio web.
<br>bewom.es no garantiza la ausencia de posibles problemas derivados de dichos servicios, así como no se hace responsable en ningún caso y bajo ningún concepto de los problemas que el usuario pueda experimentar debidos al uso de los servicios de terceros hallados en el sitio web, sean de la índole que sean.
<br><br>
<b>8 - CONTACTO.</b><br>
A efectos de contacto con la dirección de bewom.es acerca de los anteriores Términos y Condiciones de Servicio, dirigirse a donaciones@bewom.es.